services:
  efemeria:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3003:3003"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/healthq4tHyrFrwQqfRbAQ"]
      interval: 5m
      timeout: 10s
      retries: 2
      start_period: 40s
